-
  name: 'authorization page'
  uriPattern:    'authorize'
  defaults:
        '@package':    'Kyoki.OAuth2'
        '@controller': 'OAuth'
        '@format':     'html'
        '@action':     'authorize'
-
  name: 'token endpoint page'
  uriPattern:    'token'
  defaults:
        '@package':    'Kyoki.OAuth2'
        '@controller': 'Token'
        '@format':     'html'
        '@action':     'token'
