Kyoki:
  OAuth2:
    Client:
      DefaultPartyUUID: 'd07b121f-5940-4326-844b-87d3654a38ea'
      PartyClassName: 'F2\TuitLawyer\Domain\Model\Usuario'

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          OAuthClientProviderHttpBasic:
            provider: Kyoki\OAuth2\Security\Authentication\Provider\ClientIdSecretProvider
            token: Kyoki\OAuth2\Security\Authentication\Token\ClientIdSecretHttpBasic
            requestPatterns:
              controllerObjectName: Kyoki\OAuth2\Controller\TokenController
            entryPoint: HttpBasic
            entryPointOptions:
              realm: 'OAuth2 Client Authentication'
          OAuthClientProvider:
            provider: Kyoki\OAuth2\Security\Authentication\Provider\ClientIdSecretProvider
            token: Kyoki\OAuth2\Security\Authentication\Token\ClientIdSecret
            requestPatterns:
              controllerObjectName: Kyoki\OAuth2\Controller\TokenController