Kyoki:
  OAuth2:
    Client:
      DefaultPartyUUID: 'd07b121f-5940-4326-844b-87d3654a38ea'
      PartyClassName: 'F2\TuitLawyer\Domain\Model\Usuario'

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          OAuthClientProvider:
            provider: Kyoki\OAuth2\Security\Authentication\Provider\ClientIdSecretProvider
            token: Kyoki\OAuth2\Security\Authentication\Token\ClientIdSecret
            requestPatterns:
              controllerObjectName: Kyoki\OAuth2\Controller\TokenController
          OAuthClientProviderHttpBasic:
            provider: Kyoki\OAuth2\Security\Authentication\Provider\ClientIdSecretProvider
            token: Kyoki\OAuth2\Security\Authentication\Token\ClientIdSecretHttpBasic
            requestPatterns:
              controllerObjectName: Kyoki\OAuth2\Controller\TokenController
            entryPoint: HttpBasic
            entryPointOptions:
              realm: 'OAuth2 Client Authentication'
#          OAuthTokenProvider:
#            provider: Kyoki\OAuth2\Security\Authentication\Provider\AccessTokenProvider
#            token: Kyoki\OAuth2\Security\Authentication\Token\AccessTokenHttpBasic
#            requestPatterns:
#              controllerObjectName: My\Package\Controller\ResourceController
#            entryPoint: HttpBasic
#            entryPointOptions:
#              realm: 'OAuth2 Access Token Authentication'
#          DefaultProvider:
#            provider: PersistedUsernamePasswordProvider
#            entryPoint: 'WebRedirect'
#            requestPatterns:
#              controllerObjectName: (?!Kyoki\OAuth2\Controller\TokenController)
#              controllerObjectName: .*
#            entryPointOptions:
#              uri: 'login'